# Generated by Django 5.2.1 on 2025-05-25 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='date',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='mode',
        ),
    ]
