# Generated by Django 5.2.1 on 2025-05-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_agendamento_cpf_remove_agendamento_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='subject',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='gender',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='hour',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='mode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
