# Generated by Django 5.2.1 on 2025-05-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_agendamento_subject_agendamento_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
