# Generated by Django 5.2.1 on 2025-05-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_agendamento_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='hour',
            new_name='time',
        ),
    ]
