# Generated by Django 5.2.1 on 2025-05-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_hour_agendamento_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='time',
            new_name='hour',
        ),
    ]
